package dev.wckdboy.autobot.core.security.crypto

import java.nio.ByteBuffer
import java.security.GeneralSecurityException
import javax.crypto.Cipher
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec

/**
 * Self-describing AES-256-GCM envelope. Pure JVM so it can be unit tested without a device.
 *
 * Wire format (all lengths in bytes):
 * ```
 * +---------+--------+---------+--------------------------+
 * | version | ivLen  |   iv    | ciphertext || 16B GCM tag |
 * |   1     |   1    | ivLen   |          rest            |
 * +---------+--------+---------+--------------------------+
 * ```
 *
 * The IV is always generated by the cipher provider (`Cipher.init` without parameters), which is
 * mandatory for Android Keystore keys with randomized encryption and avoids IV reuse bugs.
 * Optional associated data (AAD) binds a ciphertext to its context (e.g. a secret's reference),
 * so blobs cannot be swapped between slots without detection.
 */
object AesGcmEnvelope {
    const val VERSION: Byte = 1
    const val GCM_IV_LENGTH = 12
    const val GCM_TAG_BITS = 128
    private const val TRANSFORMATION = "AES/GCM/NoPadding"
    private const val HEADER_LENGTH = 2

    /** Decoded but still encrypted envelope parts. */
    class Parts(val iv: ByteArray, val ciphertext: ByteArray) {
        override fun toString(): String = "Parts(iv=${iv.size}B, ciphertext=${ciphertext.size}B)"
    }

    /** Encrypts [plaintext] with [key] and returns an encoded envelope. */
    fun seal(key: SecretKey, plaintext: ByteArray, aad: ByteArray? = null): ByteArray {
        val cipher = Cipher.getInstance(TRANSFORMATION)
        cipher.init(Cipher.ENCRYPT_MODE, key)
        aad?.let(cipher::updateAAD)
        val ciphertext = cipher.doFinal(plaintext)
        return encode(Parts(cipher.iv, ciphertext))
    }

    /**
     * Decrypts an envelope produced by [seal].
     *
     * @throws GeneralSecurityException if the envelope is malformed, was tampered with, the AAD
     * does not match, or the key is wrong.
     */
    fun open(key: SecretKey, envelope: ByteArray, aad: ByteArray? = null): ByteArray {
        val parts = decode(envelope)
        val cipher = Cipher.getInstance(TRANSFORMATION)
        cipher.init(Cipher.DECRYPT_MODE, key, GCMParameterSpec(GCM_TAG_BITS, parts.iv))
        aad?.let(cipher::updateAAD)
        return cipher.doFinal(parts.ciphertext)
    }

    /** Serializes [parts] into the wire format. */
    fun encode(parts: Parts): ByteArray {
        require(parts.iv.size in 1..255) { "Invalid IV length" }
        return ByteBuffer.allocate(HEADER_LENGTH + parts.iv.size + parts.ciphertext.size)
            .put(VERSION)
            .put(parts.iv.size.toByte())
            .put(parts.iv)
            .put(parts.ciphertext)
            .array()
    }

    /**
     * Parses the wire format.
     *
     * @throws GeneralSecurityException on unknown version or truncated input.
     */
    fun decode(envelope: ByteArray): Parts {
        if (envelope.size < HEADER_LENGTH) throw GeneralSecurityException("Envelope too short")
        val version = envelope[0]
        if (version != VERSION) throw GeneralSecurityException("Unsupported envelope version $version")
        val ivLength = envelope[1].toInt() and 0xFF
        if (ivLength != GCM_IV_LENGTH) throw GeneralSecurityException("Unexpected IV length $ivLength")
        val tagBytes = GCM_TAG_BITS / 8
        if (envelope.size < HEADER_LENGTH + ivLength + tagBytes) {
            throw GeneralSecurityException("Envelope truncated")
        }
        val iv = envelope.copyOfRange(HEADER_LENGTH, HEADER_LENGTH + ivLength)
        val ciphertext = envelope.copyOfRange(HEADER_LENGTH + ivLength, envelope.size)
        return Parts(iv, ciphertext)
    }
}
